package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Message implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgtitle
     *
     * @mbg.generated
     */
    private String msgtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mdate
     *
     * @mbg.generated
     */
    private String mdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgstate
     *
     * @mbg.generated
     */
    private Integer msgstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.reciptant
     *
     * @mbg.generated
     */
    private String reciptant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mid
     *
     * @return the value of message.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mid
     *
     * @param mid the value for message.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgtitle
     *
     * @return the value of message.msgtitle
     *
     * @mbg.generated
     */
    public String getMsgtitle() {
        return msgtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgtitle
     *
     * @param msgtitle the value for message.msgtitle
     *
     * @mbg.generated
     */
    public void setMsgtitle(String msgtitle) {
        this.msgtitle = msgtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mdate
     *
     * @return the value of message.mdate
     *
     * @mbg.generated
     */
    public String getMdate() {
        return mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mdate
     *
     * @param mdate the value for message.mdate
     *
     * @mbg.generated
     */
    public void setMdate(String mdate) {
        this.mdate = mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg
     *
     * @return the value of message.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg
     *
     * @param msg the value for message.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgstate
     *
     * @return the value of message.msgstate
     *
     * @mbg.generated
     */
    public Integer getMsgstate() {
        return msgstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgstate
     *
     * @param msgstate the value for message.msgstate
     *
     * @mbg.generated
     */
    public void setMsgstate(Integer msgstate) {
        this.msgstate = msgstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.reciptant
     *
     * @return the value of message.reciptant
     *
     * @mbg.generated
     */
    public String getReciptant() {
        return reciptant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.reciptant
     *
     * @param reciptant the value for message.reciptant
     *
     * @mbg.generated
     */
    public void setReciptant(String reciptant) {
        this.reciptant = reciptant;
    }
}