package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pdcomment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Pdcomment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.comid
     *
     * @mbg.generated
     */
    private Integer comid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.pdtitle
     *
     * @mbg.generated
     */
    private String pdtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.comowner
     *
     * @mbg.generated
     */
    private String comowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.comdate
     *
     * @mbg.generated
     */
    private String comdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.uimg
     *
     * @mbg.generated
     */
    private String uimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdcomment.parent
     *
     * @mbg.generated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.comid
     *
     * @return the value of pdcomment.comid
     *
     * @mbg.generated
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.comid
     *
     * @param comid the value for pdcomment.comid
     *
     * @mbg.generated
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.pdtitle
     *
     * @return the value of pdcomment.pdtitle
     *
     * @mbg.generated
     */
    public String getPdtitle() {
        return pdtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.pdtitle
     *
     * @param pdtitle the value for pdcomment.pdtitle
     *
     * @mbg.generated
     */
    public void setPdtitle(String pdtitle) {
        this.pdtitle = pdtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.comowner
     *
     * @return the value of pdcomment.comowner
     *
     * @mbg.generated
     */
    public String getComowner() {
        return comowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.comowner
     *
     * @param comowner the value for pdcomment.comowner
     *
     * @mbg.generated
     */
    public void setComowner(String comowner) {
        this.comowner = comowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.content
     *
     * @return the value of pdcomment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.content
     *
     * @param content the value for pdcomment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.comdate
     *
     * @return the value of pdcomment.comdate
     *
     * @mbg.generated
     */
    public String getComdate() {
        return comdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.comdate
     *
     * @param comdate the value for pdcomment.comdate
     *
     * @mbg.generated
     */
    public void setComdate(String comdate) {
        this.comdate = comdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.uimg
     *
     * @return the value of pdcomment.uimg
     *
     * @mbg.generated
     */
    public String getUimg() {
        return uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.uimg
     *
     * @param uimg the value for pdcomment.uimg
     *
     * @mbg.generated
     */
    public void setUimg(String uimg) {
        this.uimg = uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdcomment.parent
     *
     * @return the value of pdcomment.parent
     *
     * @mbg.generated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdcomment.parent
     *
     * @param parent the value for pdcomment.parent
     *
     * @mbg.generated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}