package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PdcommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public PdcommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComidIsNull() {
            addCriterion("comid is null");
            return (Criteria) this;
        }

        public Criteria andComidIsNotNull() {
            addCriterion("comid is not null");
            return (Criteria) this;
        }

        public Criteria andComidEqualTo(Integer value) {
            addCriterion("comid =", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotEqualTo(Integer value) {
            addCriterion("comid <>", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidGreaterThan(Integer value) {
            addCriterion("comid >", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidGreaterThanOrEqualTo(Integer value) {
            addCriterion("comid >=", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidLessThan(Integer value) {
            addCriterion("comid <", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidLessThanOrEqualTo(Integer value) {
            addCriterion("comid <=", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidIn(List<Integer> values) {
            addCriterion("comid in", values, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotIn(List<Integer> values) {
            addCriterion("comid not in", values, "comid");
            return (Criteria) this;
        }

        public Criteria andComidBetween(Integer value1, Integer value2) {
            addCriterion("comid between", value1, value2, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotBetween(Integer value1, Integer value2) {
            addCriterion("comid not between", value1, value2, "comid");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNull() {
            addCriterion("pdtitle is null");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNotNull() {
            addCriterion("pdtitle is not null");
            return (Criteria) this;
        }

        public Criteria andPdtitleEqualTo(String value) {
            addCriterion("pdtitle =", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotEqualTo(String value) {
            addCriterion("pdtitle <>", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThan(String value) {
            addCriterion("pdtitle >", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThanOrEqualTo(String value) {
            addCriterion("pdtitle >=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThan(String value) {
            addCriterion("pdtitle <", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThanOrEqualTo(String value) {
            addCriterion("pdtitle <=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLike(String value) {
            addCriterion("pdtitle like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotLike(String value) {
            addCriterion("pdtitle not like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleIn(List<String> values) {
            addCriterion("pdtitle in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotIn(List<String> values) {
            addCriterion("pdtitle not in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleBetween(String value1, String value2) {
            addCriterion("pdtitle between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotBetween(String value1, String value2) {
            addCriterion("pdtitle not between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andComownerIsNull() {
            addCriterion("comowner is null");
            return (Criteria) this;
        }

        public Criteria andComownerIsNotNull() {
            addCriterion("comowner is not null");
            return (Criteria) this;
        }

        public Criteria andComownerEqualTo(String value) {
            addCriterion("comowner =", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerNotEqualTo(String value) {
            addCriterion("comowner <>", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerGreaterThan(String value) {
            addCriterion("comowner >", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerGreaterThanOrEqualTo(String value) {
            addCriterion("comowner >=", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerLessThan(String value) {
            addCriterion("comowner <", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerLessThanOrEqualTo(String value) {
            addCriterion("comowner <=", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerLike(String value) {
            addCriterion("comowner like", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerNotLike(String value) {
            addCriterion("comowner not like", value, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerIn(List<String> values) {
            addCriterion("comowner in", values, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerNotIn(List<String> values) {
            addCriterion("comowner not in", values, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerBetween(String value1, String value2) {
            addCriterion("comowner between", value1, value2, "comowner");
            return (Criteria) this;
        }

        public Criteria andComownerNotBetween(String value1, String value2) {
            addCriterion("comowner not between", value1, value2, "comowner");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andComdateIsNull() {
            addCriterion("comdate is null");
            return (Criteria) this;
        }

        public Criteria andComdateIsNotNull() {
            addCriterion("comdate is not null");
            return (Criteria) this;
        }

        public Criteria andComdateEqualTo(String value) {
            addCriterion("comdate =", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateNotEqualTo(String value) {
            addCriterion("comdate <>", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateGreaterThan(String value) {
            addCriterion("comdate >", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateGreaterThanOrEqualTo(String value) {
            addCriterion("comdate >=", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateLessThan(String value) {
            addCriterion("comdate <", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateLessThanOrEqualTo(String value) {
            addCriterion("comdate <=", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateLike(String value) {
            addCriterion("comdate like", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateNotLike(String value) {
            addCriterion("comdate not like", value, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateIn(List<String> values) {
            addCriterion("comdate in", values, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateNotIn(List<String> values) {
            addCriterion("comdate not in", values, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateBetween(String value1, String value2) {
            addCriterion("comdate between", value1, value2, "comdate");
            return (Criteria) this;
        }

        public Criteria andComdateNotBetween(String value1, String value2) {
            addCriterion("comdate not between", value1, value2, "comdate");
            return (Criteria) this;
        }

        public Criteria andUimgIsNull() {
            addCriterion("uimg is null");
            return (Criteria) this;
        }

        public Criteria andUimgIsNotNull() {
            addCriterion("uimg is not null");
            return (Criteria) this;
        }

        public Criteria andUimgEqualTo(String value) {
            addCriterion("uimg =", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotEqualTo(String value) {
            addCriterion("uimg <>", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgGreaterThan(String value) {
            addCriterion("uimg >", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgGreaterThanOrEqualTo(String value) {
            addCriterion("uimg >=", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLessThan(String value) {
            addCriterion("uimg <", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLessThanOrEqualTo(String value) {
            addCriterion("uimg <=", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLike(String value) {
            addCriterion("uimg like", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotLike(String value) {
            addCriterion("uimg not like", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgIn(List<String> values) {
            addCriterion("uimg in", values, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotIn(List<String> values) {
            addCriterion("uimg not in", values, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgBetween(String value1, String value2) {
            addCriterion("uimg between", value1, value2, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotBetween(String value1, String value2) {
            addCriterion("uimg not between", value1, value2, "uimg");
            return (Criteria) this;
        }

        public Criteria andParentIsNull() {
            addCriterion("parent is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(Integer value) {
            addCriterion("parent =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(Integer value) {
            addCriterion("parent <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(Integer value) {
            addCriterion("parent >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(Integer value) {
            addCriterion("parent <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(Integer value) {
            addCriterion("parent <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<Integer> values) {
            addCriterion("parent in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<Integer> values) {
            addCriterion("parent not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(Integer value1, Integer value2) {
            addCriterion("parent between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(Integer value1, Integer value2) {
            addCriterion("parent not between", value1, value2, "parent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdcomment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}