package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PdkeepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public PdkeepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPdkeepidIsNull() {
            addCriterion("pdkeepid is null");
            return (Criteria) this;
        }

        public Criteria andPdkeepidIsNotNull() {
            addCriterion("pdkeepid is not null");
            return (Criteria) this;
        }

        public Criteria andPdkeepidEqualTo(Integer value) {
            addCriterion("pdkeepid =", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidNotEqualTo(Integer value) {
            addCriterion("pdkeepid <>", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidGreaterThan(Integer value) {
            addCriterion("pdkeepid >", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pdkeepid >=", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidLessThan(Integer value) {
            addCriterion("pdkeepid <", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidLessThanOrEqualTo(Integer value) {
            addCriterion("pdkeepid <=", value, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidIn(List<Integer> values) {
            addCriterion("pdkeepid in", values, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidNotIn(List<Integer> values) {
            addCriterion("pdkeepid not in", values, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidBetween(Integer value1, Integer value2) {
            addCriterion("pdkeepid between", value1, value2, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdkeepidNotBetween(Integer value1, Integer value2) {
            addCriterion("pdkeepid not between", value1, value2, "pdkeepid");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNull() {
            addCriterion("pdtitle is null");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNotNull() {
            addCriterion("pdtitle is not null");
            return (Criteria) this;
        }

        public Criteria andPdtitleEqualTo(String value) {
            addCriterion("pdtitle =", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotEqualTo(String value) {
            addCriterion("pdtitle <>", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThan(String value) {
            addCriterion("pdtitle >", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThanOrEqualTo(String value) {
            addCriterion("pdtitle >=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThan(String value) {
            addCriterion("pdtitle <", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThanOrEqualTo(String value) {
            addCriterion("pdtitle <=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLike(String value) {
            addCriterion("pdtitle like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotLike(String value) {
            addCriterion("pdtitle not like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleIn(List<String> values) {
            addCriterion("pdtitle in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotIn(List<String> values) {
            addCriterion("pdtitle not in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleBetween(String value1, String value2) {
            addCriterion("pdtitle between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotBetween(String value1, String value2) {
            addCriterion("pdtitle not between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdkeeperIsNull() {
            addCriterion("pdkeeper is null");
            return (Criteria) this;
        }

        public Criteria andPdkeeperIsNotNull() {
            addCriterion("pdkeeper is not null");
            return (Criteria) this;
        }

        public Criteria andPdkeeperEqualTo(String value) {
            addCriterion("pdkeeper =", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperNotEqualTo(String value) {
            addCriterion("pdkeeper <>", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperGreaterThan(String value) {
            addCriterion("pdkeeper >", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperGreaterThanOrEqualTo(String value) {
            addCriterion("pdkeeper >=", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperLessThan(String value) {
            addCriterion("pdkeeper <", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperLessThanOrEqualTo(String value) {
            addCriterion("pdkeeper <=", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperLike(String value) {
            addCriterion("pdkeeper like", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperNotLike(String value) {
            addCriterion("pdkeeper not like", value, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperIn(List<String> values) {
            addCriterion("pdkeeper in", values, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperNotIn(List<String> values) {
            addCriterion("pdkeeper not in", values, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperBetween(String value1, String value2) {
            addCriterion("pdkeeper between", value1, value2, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeeperNotBetween(String value1, String value2) {
            addCriterion("pdkeeper not between", value1, value2, "pdkeeper");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataIsNull() {
            addCriterion("pdkeepdata is null");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataIsNotNull() {
            addCriterion("pdkeepdata is not null");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataEqualTo(String value) {
            addCriterion("pdkeepdata =", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataNotEqualTo(String value) {
            addCriterion("pdkeepdata <>", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataGreaterThan(String value) {
            addCriterion("pdkeepdata >", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataGreaterThanOrEqualTo(String value) {
            addCriterion("pdkeepdata >=", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataLessThan(String value) {
            addCriterion("pdkeepdata <", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataLessThanOrEqualTo(String value) {
            addCriterion("pdkeepdata <=", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataLike(String value) {
            addCriterion("pdkeepdata like", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataNotLike(String value) {
            addCriterion("pdkeepdata not like", value, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataIn(List<String> values) {
            addCriterion("pdkeepdata in", values, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataNotIn(List<String> values) {
            addCriterion("pdkeepdata not in", values, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataBetween(String value1, String value2) {
            addCriterion("pdkeepdata between", value1, value2, "pdkeepdata");
            return (Criteria) this;
        }

        public Criteria andPdkeepdataNotBetween(String value1, String value2) {
            addCriterion("pdkeepdata not between", value1, value2, "pdkeepdata");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdkeep
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdkeep
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}