package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PdloveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public PdloveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPdloveidIsNull() {
            addCriterion("pdloveid is null");
            return (Criteria) this;
        }

        public Criteria andPdloveidIsNotNull() {
            addCriterion("pdloveid is not null");
            return (Criteria) this;
        }

        public Criteria andPdloveidEqualTo(Integer value) {
            addCriterion("pdloveid =", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidNotEqualTo(Integer value) {
            addCriterion("pdloveid <>", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidGreaterThan(Integer value) {
            addCriterion("pdloveid >", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pdloveid >=", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidLessThan(Integer value) {
            addCriterion("pdloveid <", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidLessThanOrEqualTo(Integer value) {
            addCriterion("pdloveid <=", value, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidIn(List<Integer> values) {
            addCriterion("pdloveid in", values, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidNotIn(List<Integer> values) {
            addCriterion("pdloveid not in", values, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidBetween(Integer value1, Integer value2) {
            addCriterion("pdloveid between", value1, value2, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdloveidNotBetween(Integer value1, Integer value2) {
            addCriterion("pdloveid not between", value1, value2, "pdloveid");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNull() {
            addCriterion("pdtitle is null");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNotNull() {
            addCriterion("pdtitle is not null");
            return (Criteria) this;
        }

        public Criteria andPdtitleEqualTo(String value) {
            addCriterion("pdtitle =", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotEqualTo(String value) {
            addCriterion("pdtitle <>", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThan(String value) {
            addCriterion("pdtitle >", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThanOrEqualTo(String value) {
            addCriterion("pdtitle >=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThan(String value) {
            addCriterion("pdtitle <", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThanOrEqualTo(String value) {
            addCriterion("pdtitle <=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLike(String value) {
            addCriterion("pdtitle like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotLike(String value) {
            addCriterion("pdtitle not like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleIn(List<String> values) {
            addCriterion("pdtitle in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotIn(List<String> values) {
            addCriterion("pdtitle not in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleBetween(String value1, String value2) {
            addCriterion("pdtitle between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotBetween(String value1, String value2) {
            addCriterion("pdtitle not between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdloveownerIsNull() {
            addCriterion("pdloveowner is null");
            return (Criteria) this;
        }

        public Criteria andPdloveownerIsNotNull() {
            addCriterion("pdloveowner is not null");
            return (Criteria) this;
        }

        public Criteria andPdloveownerEqualTo(String value) {
            addCriterion("pdloveowner =", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerNotEqualTo(String value) {
            addCriterion("pdloveowner <>", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerGreaterThan(String value) {
            addCriterion("pdloveowner >", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerGreaterThanOrEqualTo(String value) {
            addCriterion("pdloveowner >=", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerLessThan(String value) {
            addCriterion("pdloveowner <", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerLessThanOrEqualTo(String value) {
            addCriterion("pdloveowner <=", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerLike(String value) {
            addCriterion("pdloveowner like", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerNotLike(String value) {
            addCriterion("pdloveowner not like", value, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerIn(List<String> values) {
            addCriterion("pdloveowner in", values, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerNotIn(List<String> values) {
            addCriterion("pdloveowner not in", values, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerBetween(String value1, String value2) {
            addCriterion("pdloveowner between", value1, value2, "pdloveowner");
            return (Criteria) this;
        }

        public Criteria andPdloveownerNotBetween(String value1, String value2) {
            addCriterion("pdloveowner not between", value1, value2, "pdloveowner");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdlove
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdlove
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}