package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pdynamic
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Pdynamic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdid
     *
     * @mbg.generated
     */
    private Integer pdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdtag
     *
     * @mbg.generated
     */
    private Integer pdtag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdtitle
     *
     * @mbg.generated
     */
    private String pdtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdimg
     *
     * @mbg.generated
     */
    private String pdimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.uimg
     *
     * @mbg.generated
     */
    private String uimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.bewrite
     *
     * @mbg.generated
     */
    private String bewrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdowner
     *
     * @mbg.generated
     */
    private String pdowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdynamic.pdtime
     *
     * @mbg.generated
     */
    private String pdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdid
     *
     * @return the value of pdynamic.pdid
     *
     * @mbg.generated
     */
    public Integer getPdid() {
        return pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdid
     *
     * @param pdid the value for pdynamic.pdid
     *
     * @mbg.generated
     */
    public void setPdid(Integer pdid) {
        this.pdid = pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdtag
     *
     * @return the value of pdynamic.pdtag
     *
     * @mbg.generated
     */
    public Integer getPdtag() {
        return pdtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdtag
     *
     * @param pdtag the value for pdynamic.pdtag
     *
     * @mbg.generated
     */
    public void setPdtag(Integer pdtag) {
        this.pdtag = pdtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdtitle
     *
     * @return the value of pdynamic.pdtitle
     *
     * @mbg.generated
     */
    public String getPdtitle() {
        return pdtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdtitle
     *
     * @param pdtitle the value for pdynamic.pdtitle
     *
     * @mbg.generated
     */
    public void setPdtitle(String pdtitle) {
        this.pdtitle = pdtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdimg
     *
     * @return the value of pdynamic.pdimg
     *
     * @mbg.generated
     */
    public String getPdimg() {
        return pdimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdimg
     *
     * @param pdimg the value for pdynamic.pdimg
     *
     * @mbg.generated
     */
    public void setPdimg(String pdimg) {
        this.pdimg = pdimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.uimg
     *
     * @return the value of pdynamic.uimg
     *
     * @mbg.generated
     */
    public String getUimg() {
        return uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.uimg
     *
     * @param uimg the value for pdynamic.uimg
     *
     * @mbg.generated
     */
    public void setUimg(String uimg) {
        this.uimg = uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.bewrite
     *
     * @return the value of pdynamic.bewrite
     *
     * @mbg.generated
     */
    public String getBewrite() {
        return bewrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.bewrite
     *
     * @param bewrite the value for pdynamic.bewrite
     *
     * @mbg.generated
     */
    public void setBewrite(String bewrite) {
        this.bewrite = bewrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdowner
     *
     * @return the value of pdynamic.pdowner
     *
     * @mbg.generated
     */
    public String getPdowner() {
        return pdowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdowner
     *
     * @param pdowner the value for pdynamic.pdowner
     *
     * @mbg.generated
     */
    public void setPdowner(String pdowner) {
        this.pdowner = pdowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdynamic.pdtime
     *
     * @return the value of pdynamic.pdtime
     *
     * @mbg.generated
     */
    public String getPdtime() {
        return pdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdynamic.pdtime
     *
     * @param pdtime the value for pdynamic.pdtime
     *
     * @mbg.generated
     */
    public void setPdtime(String pdtime) {
        this.pdtime = pdtime;
    }
}