package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PdynamicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public PdynamicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPdidIsNull() {
            addCriterion("pdid is null");
            return (Criteria) this;
        }

        public Criteria andPdidIsNotNull() {
            addCriterion("pdid is not null");
            return (Criteria) this;
        }

        public Criteria andPdidEqualTo(Integer value) {
            addCriterion("pdid =", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidNotEqualTo(Integer value) {
            addCriterion("pdid <>", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidGreaterThan(Integer value) {
            addCriterion("pdid >", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pdid >=", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidLessThan(Integer value) {
            addCriterion("pdid <", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidLessThanOrEqualTo(Integer value) {
            addCriterion("pdid <=", value, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidIn(List<Integer> values) {
            addCriterion("pdid in", values, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidNotIn(List<Integer> values) {
            addCriterion("pdid not in", values, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidBetween(Integer value1, Integer value2) {
            addCriterion("pdid between", value1, value2, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdidNotBetween(Integer value1, Integer value2) {
            addCriterion("pdid not between", value1, value2, "pdid");
            return (Criteria) this;
        }

        public Criteria andPdtagIsNull() {
            addCriterion("pdtag is null");
            return (Criteria) this;
        }

        public Criteria andPdtagIsNotNull() {
            addCriterion("pdtag is not null");
            return (Criteria) this;
        }

        public Criteria andPdtagEqualTo(Integer value) {
            addCriterion("pdtag =", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagNotEqualTo(Integer value) {
            addCriterion("pdtag <>", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagGreaterThan(Integer value) {
            addCriterion("pdtag >", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagGreaterThanOrEqualTo(Integer value) {
            addCriterion("pdtag >=", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagLessThan(Integer value) {
            addCriterion("pdtag <", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagLessThanOrEqualTo(Integer value) {
            addCriterion("pdtag <=", value, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagIn(List<Integer> values) {
            addCriterion("pdtag in", values, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagNotIn(List<Integer> values) {
            addCriterion("pdtag not in", values, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagBetween(Integer value1, Integer value2) {
            addCriterion("pdtag between", value1, value2, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtagNotBetween(Integer value1, Integer value2) {
            addCriterion("pdtag not between", value1, value2, "pdtag");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNull() {
            addCriterion("pdtitle is null");
            return (Criteria) this;
        }

        public Criteria andPdtitleIsNotNull() {
            addCriterion("pdtitle is not null");
            return (Criteria) this;
        }

        public Criteria andPdtitleEqualTo(String value) {
            addCriterion("pdtitle =", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotEqualTo(String value) {
            addCriterion("pdtitle <>", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThan(String value) {
            addCriterion("pdtitle >", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleGreaterThanOrEqualTo(String value) {
            addCriterion("pdtitle >=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThan(String value) {
            addCriterion("pdtitle <", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLessThanOrEqualTo(String value) {
            addCriterion("pdtitle <=", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleLike(String value) {
            addCriterion("pdtitle like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotLike(String value) {
            addCriterion("pdtitle not like", value, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleIn(List<String> values) {
            addCriterion("pdtitle in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotIn(List<String> values) {
            addCriterion("pdtitle not in", values, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleBetween(String value1, String value2) {
            addCriterion("pdtitle between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdtitleNotBetween(String value1, String value2) {
            addCriterion("pdtitle not between", value1, value2, "pdtitle");
            return (Criteria) this;
        }

        public Criteria andPdimgIsNull() {
            addCriterion("pdimg is null");
            return (Criteria) this;
        }

        public Criteria andPdimgIsNotNull() {
            addCriterion("pdimg is not null");
            return (Criteria) this;
        }

        public Criteria andPdimgEqualTo(String value) {
            addCriterion("pdimg =", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgNotEqualTo(String value) {
            addCriterion("pdimg <>", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgGreaterThan(String value) {
            addCriterion("pdimg >", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgGreaterThanOrEqualTo(String value) {
            addCriterion("pdimg >=", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgLessThan(String value) {
            addCriterion("pdimg <", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgLessThanOrEqualTo(String value) {
            addCriterion("pdimg <=", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgLike(String value) {
            addCriterion("pdimg like", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgNotLike(String value) {
            addCriterion("pdimg not like", value, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgIn(List<String> values) {
            addCriterion("pdimg in", values, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgNotIn(List<String> values) {
            addCriterion("pdimg not in", values, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgBetween(String value1, String value2) {
            addCriterion("pdimg between", value1, value2, "pdimg");
            return (Criteria) this;
        }

        public Criteria andPdimgNotBetween(String value1, String value2) {
            addCriterion("pdimg not between", value1, value2, "pdimg");
            return (Criteria) this;
        }

        public Criteria andUimgIsNull() {
            addCriterion("uimg is null");
            return (Criteria) this;
        }

        public Criteria andUimgIsNotNull() {
            addCriterion("uimg is not null");
            return (Criteria) this;
        }

        public Criteria andUimgEqualTo(String value) {
            addCriterion("uimg =", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotEqualTo(String value) {
            addCriterion("uimg <>", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgGreaterThan(String value) {
            addCriterion("uimg >", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgGreaterThanOrEqualTo(String value) {
            addCriterion("uimg >=", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLessThan(String value) {
            addCriterion("uimg <", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLessThanOrEqualTo(String value) {
            addCriterion("uimg <=", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgLike(String value) {
            addCriterion("uimg like", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotLike(String value) {
            addCriterion("uimg not like", value, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgIn(List<String> values) {
            addCriterion("uimg in", values, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotIn(List<String> values) {
            addCriterion("uimg not in", values, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgBetween(String value1, String value2) {
            addCriterion("uimg between", value1, value2, "uimg");
            return (Criteria) this;
        }

        public Criteria andUimgNotBetween(String value1, String value2) {
            addCriterion("uimg not between", value1, value2, "uimg");
            return (Criteria) this;
        }

        public Criteria andBewriteIsNull() {
            addCriterion("bewrite is null");
            return (Criteria) this;
        }

        public Criteria andBewriteIsNotNull() {
            addCriterion("bewrite is not null");
            return (Criteria) this;
        }

        public Criteria andBewriteEqualTo(String value) {
            addCriterion("bewrite =", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteNotEqualTo(String value) {
            addCriterion("bewrite <>", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteGreaterThan(String value) {
            addCriterion("bewrite >", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteGreaterThanOrEqualTo(String value) {
            addCriterion("bewrite >=", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteLessThan(String value) {
            addCriterion("bewrite <", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteLessThanOrEqualTo(String value) {
            addCriterion("bewrite <=", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteLike(String value) {
            addCriterion("bewrite like", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteNotLike(String value) {
            addCriterion("bewrite not like", value, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteIn(List<String> values) {
            addCriterion("bewrite in", values, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteNotIn(List<String> values) {
            addCriterion("bewrite not in", values, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteBetween(String value1, String value2) {
            addCriterion("bewrite between", value1, value2, "bewrite");
            return (Criteria) this;
        }

        public Criteria andBewriteNotBetween(String value1, String value2) {
            addCriterion("bewrite not between", value1, value2, "bewrite");
            return (Criteria) this;
        }

        public Criteria andPdownerIsNull() {
            addCriterion("pdowner is null");
            return (Criteria) this;
        }

        public Criteria andPdownerIsNotNull() {
            addCriterion("pdowner is not null");
            return (Criteria) this;
        }

        public Criteria andPdownerEqualTo(String value) {
            addCriterion("pdowner =", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerNotEqualTo(String value) {
            addCriterion("pdowner <>", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerGreaterThan(String value) {
            addCriterion("pdowner >", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerGreaterThanOrEqualTo(String value) {
            addCriterion("pdowner >=", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerLessThan(String value) {
            addCriterion("pdowner <", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerLessThanOrEqualTo(String value) {
            addCriterion("pdowner <=", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerLike(String value) {
            addCriterion("pdowner like", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerNotLike(String value) {
            addCriterion("pdowner not like", value, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerIn(List<String> values) {
            addCriterion("pdowner in", values, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerNotIn(List<String> values) {
            addCriterion("pdowner not in", values, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerBetween(String value1, String value2) {
            addCriterion("pdowner between", value1, value2, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdownerNotBetween(String value1, String value2) {
            addCriterion("pdowner not between", value1, value2, "pdowner");
            return (Criteria) this;
        }

        public Criteria andPdtimeIsNull() {
            addCriterion("pdtime is null");
            return (Criteria) this;
        }

        public Criteria andPdtimeIsNotNull() {
            addCriterion("pdtime is not null");
            return (Criteria) this;
        }

        public Criteria andPdtimeEqualTo(String value) {
            addCriterion("pdtime =", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeNotEqualTo(String value) {
            addCriterion("pdtime <>", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeGreaterThan(String value) {
            addCriterion("pdtime >", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeGreaterThanOrEqualTo(String value) {
            addCriterion("pdtime >=", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeLessThan(String value) {
            addCriterion("pdtime <", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeLessThanOrEqualTo(String value) {
            addCriterion("pdtime <=", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeLike(String value) {
            addCriterion("pdtime like", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeNotLike(String value) {
            addCriterion("pdtime not like", value, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeIn(List<String> values) {
            addCriterion("pdtime in", values, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeNotIn(List<String> values) {
            addCriterion("pdtime not in", values, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeBetween(String value1, String value2) {
            addCriterion("pdtime between", value1, value2, "pdtime");
            return (Criteria) this;
        }

        public Criteria andPdtimeNotBetween(String value1, String value2) {
            addCriterion("pdtime not between", value1, value2, "pdtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdynamic
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}