package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pet
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Pet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.phost
     *
     * @mbg.generated
     */
    private String phost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.petage
     *
     * @mbg.generated
     */
    private Integer petage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.pdescription
     *
     * @mbg.generated
     */
    private String pdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.pgender
     *
     * @mbg.generated
     */
    private Integer pgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.pimg
     *
     * @mbg.generated
     */
    private String pimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.ptype
     *
     * @mbg.generated
     */
    private String ptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.pid
     *
     * @return the value of pet.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.pid
     *
     * @param pid the value for pet.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.pname
     *
     * @return the value of pet.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.pname
     *
     * @param pname the value for pet.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.phost
     *
     * @return the value of pet.phost
     *
     * @mbg.generated
     */
    public String getPhost() {
        return phost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.phost
     *
     * @param phost the value for pet.phost
     *
     * @mbg.generated
     */
    public void setPhost(String phost) {
        this.phost = phost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.petage
     *
     * @return the value of pet.petage
     *
     * @mbg.generated
     */
    public Integer getPetage() {
        return petage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.petage
     *
     * @param petage the value for pet.petage
     *
     * @mbg.generated
     */
    public void setPetage(Integer petage) {
        this.petage = petage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.pdescription
     *
     * @return the value of pet.pdescription
     *
     * @mbg.generated
     */
    public String getPdescription() {
        return pdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.pdescription
     *
     * @param pdescription the value for pet.pdescription
     *
     * @mbg.generated
     */
    public void setPdescription(String pdescription) {
        this.pdescription = pdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.pgender
     *
     * @return the value of pet.pgender
     *
     * @mbg.generated
     */
    public Integer getPgender() {
        return pgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.pgender
     *
     * @param pgender the value for pet.pgender
     *
     * @mbg.generated
     */
    public void setPgender(Integer pgender) {
        this.pgender = pgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.pimg
     *
     * @return the value of pet.pimg
     *
     * @mbg.generated
     */
    public String getPimg() {
        return pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.pimg
     *
     * @param pimg the value for pet.pimg
     *
     * @mbg.generated
     */
    public void setPimg(String pimg) {
        this.pimg = pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.ptype
     *
     * @return the value of pet.ptype
     *
     * @mbg.generated
     */
    public String getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.ptype
     *
     * @param ptype the value for pet.ptype
     *
     * @mbg.generated
     */
    public void setPtype(String ptype) {
        this.ptype = ptype;
    }
}