package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public PetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pet
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPnameIsNull() {
            addCriterion("pname is null");
            return (Criteria) this;
        }

        public Criteria andPnameIsNotNull() {
            addCriterion("pname is not null");
            return (Criteria) this;
        }

        public Criteria andPnameEqualTo(String value) {
            addCriterion("pname =", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotEqualTo(String value) {
            addCriterion("pname <>", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThan(String value) {
            addCriterion("pname >", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThanOrEqualTo(String value) {
            addCriterion("pname >=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThan(String value) {
            addCriterion("pname <", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThanOrEqualTo(String value) {
            addCriterion("pname <=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLike(String value) {
            addCriterion("pname like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotLike(String value) {
            addCriterion("pname not like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameIn(List<String> values) {
            addCriterion("pname in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotIn(List<String> values) {
            addCriterion("pname not in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameBetween(String value1, String value2) {
            addCriterion("pname between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotBetween(String value1, String value2) {
            addCriterion("pname not between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPhostIsNull() {
            addCriterion("phost is null");
            return (Criteria) this;
        }

        public Criteria andPhostIsNotNull() {
            addCriterion("phost is not null");
            return (Criteria) this;
        }

        public Criteria andPhostEqualTo(String value) {
            addCriterion("phost =", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostNotEqualTo(String value) {
            addCriterion("phost <>", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostGreaterThan(String value) {
            addCriterion("phost >", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostGreaterThanOrEqualTo(String value) {
            addCriterion("phost >=", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostLessThan(String value) {
            addCriterion("phost <", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostLessThanOrEqualTo(String value) {
            addCriterion("phost <=", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostLike(String value) {
            addCriterion("phost like", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostNotLike(String value) {
            addCriterion("phost not like", value, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostIn(List<String> values) {
            addCriterion("phost in", values, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostNotIn(List<String> values) {
            addCriterion("phost not in", values, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostBetween(String value1, String value2) {
            addCriterion("phost between", value1, value2, "phost");
            return (Criteria) this;
        }

        public Criteria andPhostNotBetween(String value1, String value2) {
            addCriterion("phost not between", value1, value2, "phost");
            return (Criteria) this;
        }

        public Criteria andPetageIsNull() {
            addCriterion("petage is null");
            return (Criteria) this;
        }

        public Criteria andPetageIsNotNull() {
            addCriterion("petage is not null");
            return (Criteria) this;
        }

        public Criteria andPetageEqualTo(Integer value) {
            addCriterion("petage =", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageNotEqualTo(Integer value) {
            addCriterion("petage <>", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageGreaterThan(Integer value) {
            addCriterion("petage >", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageGreaterThanOrEqualTo(Integer value) {
            addCriterion("petage >=", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageLessThan(Integer value) {
            addCriterion("petage <", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageLessThanOrEqualTo(Integer value) {
            addCriterion("petage <=", value, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageIn(List<Integer> values) {
            addCriterion("petage in", values, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageNotIn(List<Integer> values) {
            addCriterion("petage not in", values, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageBetween(Integer value1, Integer value2) {
            addCriterion("petage between", value1, value2, "petage");
            return (Criteria) this;
        }

        public Criteria andPetageNotBetween(Integer value1, Integer value2) {
            addCriterion("petage not between", value1, value2, "petage");
            return (Criteria) this;
        }

        public Criteria andPdescriptionIsNull() {
            addCriterion("pdescription is null");
            return (Criteria) this;
        }

        public Criteria andPdescriptionIsNotNull() {
            addCriterion("pdescription is not null");
            return (Criteria) this;
        }

        public Criteria andPdescriptionEqualTo(String value) {
            addCriterion("pdescription =", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionNotEqualTo(String value) {
            addCriterion("pdescription <>", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionGreaterThan(String value) {
            addCriterion("pdescription >", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("pdescription >=", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionLessThan(String value) {
            addCriterion("pdescription <", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionLessThanOrEqualTo(String value) {
            addCriterion("pdescription <=", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionLike(String value) {
            addCriterion("pdescription like", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionNotLike(String value) {
            addCriterion("pdescription not like", value, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionIn(List<String> values) {
            addCriterion("pdescription in", values, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionNotIn(List<String> values) {
            addCriterion("pdescription not in", values, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionBetween(String value1, String value2) {
            addCriterion("pdescription between", value1, value2, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPdescriptionNotBetween(String value1, String value2) {
            addCriterion("pdescription not between", value1, value2, "pdescription");
            return (Criteria) this;
        }

        public Criteria andPgenderIsNull() {
            addCriterion("pgender is null");
            return (Criteria) this;
        }

        public Criteria andPgenderIsNotNull() {
            addCriterion("pgender is not null");
            return (Criteria) this;
        }

        public Criteria andPgenderEqualTo(Integer value) {
            addCriterion("pgender =", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderNotEqualTo(Integer value) {
            addCriterion("pgender <>", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderGreaterThan(Integer value) {
            addCriterion("pgender >", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("pgender >=", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderLessThan(Integer value) {
            addCriterion("pgender <", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderLessThanOrEqualTo(Integer value) {
            addCriterion("pgender <=", value, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderIn(List<Integer> values) {
            addCriterion("pgender in", values, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderNotIn(List<Integer> values) {
            addCriterion("pgender not in", values, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderBetween(Integer value1, Integer value2) {
            addCriterion("pgender between", value1, value2, "pgender");
            return (Criteria) this;
        }

        public Criteria andPgenderNotBetween(Integer value1, Integer value2) {
            addCriterion("pgender not between", value1, value2, "pgender");
            return (Criteria) this;
        }

        public Criteria andPimgIsNull() {
            addCriterion("pimg is null");
            return (Criteria) this;
        }

        public Criteria andPimgIsNotNull() {
            addCriterion("pimg is not null");
            return (Criteria) this;
        }

        public Criteria andPimgEqualTo(String value) {
            addCriterion("pimg =", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgNotEqualTo(String value) {
            addCriterion("pimg <>", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgGreaterThan(String value) {
            addCriterion("pimg >", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgGreaterThanOrEqualTo(String value) {
            addCriterion("pimg >=", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgLessThan(String value) {
            addCriterion("pimg <", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgLessThanOrEqualTo(String value) {
            addCriterion("pimg <=", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgLike(String value) {
            addCriterion("pimg like", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgNotLike(String value) {
            addCriterion("pimg not like", value, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgIn(List<String> values) {
            addCriterion("pimg in", values, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgNotIn(List<String> values) {
            addCriterion("pimg not in", values, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgBetween(String value1, String value2) {
            addCriterion("pimg between", value1, value2, "pimg");
            return (Criteria) this;
        }

        public Criteria andPimgNotBetween(String value1, String value2) {
            addCriterion("pimg not between", value1, value2, "pimg");
            return (Criteria) this;
        }

        public Criteria andPtypeIsNull() {
            addCriterion("ptype is null");
            return (Criteria) this;
        }

        public Criteria andPtypeIsNotNull() {
            addCriterion("ptype is not null");
            return (Criteria) this;
        }

        public Criteria andPtypeEqualTo(String value) {
            addCriterion("ptype =", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeNotEqualTo(String value) {
            addCriterion("ptype <>", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeGreaterThan(String value) {
            addCriterion("ptype >", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ptype >=", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeLessThan(String value) {
            addCriterion("ptype <", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeLessThanOrEqualTo(String value) {
            addCriterion("ptype <=", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeLike(String value) {
            addCriterion("ptype like", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeNotLike(String value) {
            addCriterion("ptype not like", value, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeIn(List<String> values) {
            addCriterion("ptype in", values, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeNotIn(List<String> values) {
            addCriterion("ptype not in", values, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeBetween(String value1, String value2) {
            addCriterion("ptype between", value1, value2, "ptype");
            return (Criteria) this;
        }

        public Criteria andPtypeNotBetween(String value1, String value2) {
            addCriterion("ptype not between", value1, value2, "ptype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pet
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pet
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}