package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table petknowledge
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Petknowledge implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.pkid
     *
     * @mbg.generated
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.pettype
     *
     * @mbg.generated
     */
    private Integer pettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.petname
     *
     * @mbg.generated
     */
    private String petname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.characters
     *
     * @mbg.generated
     */
    private String characters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.easyOfDisease
     *
     * @mbg.generated
     */
    private String easyofdisease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.life
     *
     * @mbg.generated
     */
    private String life;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.feature
     *
     * @mbg.generated
     */
    private String feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.characterFeature
     *
     * @mbg.generated
     */
    private String characterfeature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.careKnowledge
     *
     * @mbg.generated
     */
    private String careknowledge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.feedPoints
     *
     * @mbg.generated
     */
    private String feedpoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petknowledge.coverURL
     *
     * @mbg.generated
     */
    private String coverurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.pkid
     *
     * @return the value of petknowledge.pkid
     *
     * @mbg.generated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.pkid
     *
     * @param pkid the value for petknowledge.pkid
     *
     * @mbg.generated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.pettype
     *
     * @return the value of petknowledge.pettype
     *
     * @mbg.generated
     */
    public Integer getPettype() {
        return pettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.pettype
     *
     * @param pettype the value for petknowledge.pettype
     *
     * @mbg.generated
     */
    public void setPettype(Integer pettype) {
        this.pettype = pettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.petname
     *
     * @return the value of petknowledge.petname
     *
     * @mbg.generated
     */
    public String getPetname() {
        return petname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.petname
     *
     * @param petname the value for petknowledge.petname
     *
     * @mbg.generated
     */
    public void setPetname(String petname) {
        this.petname = petname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.characters
     *
     * @return the value of petknowledge.characters
     *
     * @mbg.generated
     */
    public String getCharacters() {
        return characters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.characters
     *
     * @param characters the value for petknowledge.characters
     *
     * @mbg.generated
     */
    public void setCharacters(String characters) {
        this.characters = characters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.nation
     *
     * @return the value of petknowledge.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.nation
     *
     * @param nation the value for petknowledge.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.easyOfDisease
     *
     * @return the value of petknowledge.easyOfDisease
     *
     * @mbg.generated
     */
    public String getEasyofdisease() {
        return easyofdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.easyOfDisease
     *
     * @param easyofdisease the value for petknowledge.easyOfDisease
     *
     * @mbg.generated
     */
    public void setEasyofdisease(String easyofdisease) {
        this.easyofdisease = easyofdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.life
     *
     * @return the value of petknowledge.life
     *
     * @mbg.generated
     */
    public String getLife() {
        return life;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.life
     *
     * @param life the value for petknowledge.life
     *
     * @mbg.generated
     */
    public void setLife(String life) {
        this.life = life;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.feature
     *
     * @return the value of petknowledge.feature
     *
     * @mbg.generated
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.feature
     *
     * @param feature the value for petknowledge.feature
     *
     * @mbg.generated
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.characterFeature
     *
     * @return the value of petknowledge.characterFeature
     *
     * @mbg.generated
     */
    public String getCharacterfeature() {
        return characterfeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.characterFeature
     *
     * @param characterfeature the value for petknowledge.characterFeature
     *
     * @mbg.generated
     */
    public void setCharacterfeature(String characterfeature) {
        this.characterfeature = characterfeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.careKnowledge
     *
     * @return the value of petknowledge.careKnowledge
     *
     * @mbg.generated
     */
    public String getCareknowledge() {
        return careknowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.careKnowledge
     *
     * @param careknowledge the value for petknowledge.careKnowledge
     *
     * @mbg.generated
     */
    public void setCareknowledge(String careknowledge) {
        this.careknowledge = careknowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.feedPoints
     *
     * @return the value of petknowledge.feedPoints
     *
     * @mbg.generated
     */
    public String getFeedpoints() {
        return feedpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.feedPoints
     *
     * @param feedpoints the value for petknowledge.feedPoints
     *
     * @mbg.generated
     */
    public void setFeedpoints(String feedpoints) {
        this.feedpoints = feedpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.url
     *
     * @return the value of petknowledge.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.url
     *
     * @param url the value for petknowledge.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petknowledge.coverURL
     *
     * @return the value of petknowledge.coverURL
     *
     * @mbg.generated
     */
    public String getCoverurl() {
        return coverurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petknowledge.coverURL
     *
     * @param coverurl the value for petknowledge.coverURL
     *
     * @mbg.generated
     */
    public void setCoverurl(String coverurl) {
        this.coverurl = coverurl;
    }
}