package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table plog
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Plog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.plid
     *
     * @mbg.generated
     */
    private Integer plid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.pltitle
     *
     * @mbg.generated
     */
    private String pltitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.plimg
     *
     * @mbg.generated
     */
    private String plimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.pldate
     *
     * @mbg.generated
     */
    private String pldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.pldescription
     *
     * @mbg.generated
     */
    private String pldescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plog.plowner
     *
     * @mbg.generated
     */
    private String plowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.plid
     *
     * @return the value of plog.plid
     *
     * @mbg.generated
     */
    public Integer getPlid() {
        return plid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.plid
     *
     * @param plid the value for plog.plid
     *
     * @mbg.generated
     */
    public void setPlid(Integer plid) {
        this.plid = plid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.pltitle
     *
     * @return the value of plog.pltitle
     *
     * @mbg.generated
     */
    public String getPltitle() {
        return pltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.pltitle
     *
     * @param pltitle the value for plog.pltitle
     *
     * @mbg.generated
     */
    public void setPltitle(String pltitle) {
        this.pltitle = pltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.plimg
     *
     * @return the value of plog.plimg
     *
     * @mbg.generated
     */
    public String getPlimg() {
        return plimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.plimg
     *
     * @param plimg the value for plog.plimg
     *
     * @mbg.generated
     */
    public void setPlimg(String plimg) {
        this.plimg = plimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.pldate
     *
     * @return the value of plog.pldate
     *
     * @mbg.generated
     */
    public String getPldate() {
        return pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.pldate
     *
     * @param pldate the value for plog.pldate
     *
     * @mbg.generated
     */
    public void setPldate(String pldate) {
        this.pldate = pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.pldescription
     *
     * @return the value of plog.pldescription
     *
     * @mbg.generated
     */
    public String getPldescription() {
        return pldescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.pldescription
     *
     * @param pldescription the value for plog.pldescription
     *
     * @mbg.generated
     */
    public void setPldescription(String pldescription) {
        this.pldescription = pldescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plog.plowner
     *
     * @return the value of plog.plowner
     *
     * @mbg.generated
     */
    public String getPlowner() {
        return plowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plog.plowner
     *
     * @param plowner the value for plog.plowner
     *
     * @mbg.generated
     */
    public void setPlowner(String plowner) {
        this.plowner = plowner;
    }
}