package com.example.webpet.entity;

import java.util.ArrayList;
import java.util.List;

public class PlogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plog
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plog
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plog
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public PlogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plog
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlidIsNull() {
            addCriterion("plid is null");
            return (Criteria) this;
        }

        public Criteria andPlidIsNotNull() {
            addCriterion("plid is not null");
            return (Criteria) this;
        }

        public Criteria andPlidEqualTo(Integer value) {
            addCriterion("plid =", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidNotEqualTo(Integer value) {
            addCriterion("plid <>", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidGreaterThan(Integer value) {
            addCriterion("plid >", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidGreaterThanOrEqualTo(Integer value) {
            addCriterion("plid >=", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidLessThan(Integer value) {
            addCriterion("plid <", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidLessThanOrEqualTo(Integer value) {
            addCriterion("plid <=", value, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidIn(List<Integer> values) {
            addCriterion("plid in", values, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidNotIn(List<Integer> values) {
            addCriterion("plid not in", values, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidBetween(Integer value1, Integer value2) {
            addCriterion("plid between", value1, value2, "plid");
            return (Criteria) this;
        }

        public Criteria andPlidNotBetween(Integer value1, Integer value2) {
            addCriterion("plid not between", value1, value2, "plid");
            return (Criteria) this;
        }

        public Criteria andPltitleIsNull() {
            addCriterion("pltitle is null");
            return (Criteria) this;
        }

        public Criteria andPltitleIsNotNull() {
            addCriterion("pltitle is not null");
            return (Criteria) this;
        }

        public Criteria andPltitleEqualTo(String value) {
            addCriterion("pltitle =", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleNotEqualTo(String value) {
            addCriterion("pltitle <>", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleGreaterThan(String value) {
            addCriterion("pltitle >", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleGreaterThanOrEqualTo(String value) {
            addCriterion("pltitle >=", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleLessThan(String value) {
            addCriterion("pltitle <", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleLessThanOrEqualTo(String value) {
            addCriterion("pltitle <=", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleLike(String value) {
            addCriterion("pltitle like", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleNotLike(String value) {
            addCriterion("pltitle not like", value, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleIn(List<String> values) {
            addCriterion("pltitle in", values, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleNotIn(List<String> values) {
            addCriterion("pltitle not in", values, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleBetween(String value1, String value2) {
            addCriterion("pltitle between", value1, value2, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPltitleNotBetween(String value1, String value2) {
            addCriterion("pltitle not between", value1, value2, "pltitle");
            return (Criteria) this;
        }

        public Criteria andPlimgIsNull() {
            addCriterion("plimg is null");
            return (Criteria) this;
        }

        public Criteria andPlimgIsNotNull() {
            addCriterion("plimg is not null");
            return (Criteria) this;
        }

        public Criteria andPlimgEqualTo(String value) {
            addCriterion("plimg =", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgNotEqualTo(String value) {
            addCriterion("plimg <>", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgGreaterThan(String value) {
            addCriterion("plimg >", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgGreaterThanOrEqualTo(String value) {
            addCriterion("plimg >=", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgLessThan(String value) {
            addCriterion("plimg <", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgLessThanOrEqualTo(String value) {
            addCriterion("plimg <=", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgLike(String value) {
            addCriterion("plimg like", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgNotLike(String value) {
            addCriterion("plimg not like", value, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgIn(List<String> values) {
            addCriterion("plimg in", values, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgNotIn(List<String> values) {
            addCriterion("plimg not in", values, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgBetween(String value1, String value2) {
            addCriterion("plimg between", value1, value2, "plimg");
            return (Criteria) this;
        }

        public Criteria andPlimgNotBetween(String value1, String value2) {
            addCriterion("plimg not between", value1, value2, "plimg");
            return (Criteria) this;
        }

        public Criteria andPldateIsNull() {
            addCriterion("pldate is null");
            return (Criteria) this;
        }

        public Criteria andPldateIsNotNull() {
            addCriterion("pldate is not null");
            return (Criteria) this;
        }

        public Criteria andPldateEqualTo(String value) {
            addCriterion("pldate =", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateNotEqualTo(String value) {
            addCriterion("pldate <>", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateGreaterThan(String value) {
            addCriterion("pldate >", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateGreaterThanOrEqualTo(String value) {
            addCriterion("pldate >=", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateLessThan(String value) {
            addCriterion("pldate <", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateLessThanOrEqualTo(String value) {
            addCriterion("pldate <=", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateLike(String value) {
            addCriterion("pldate like", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateNotLike(String value) {
            addCriterion("pldate not like", value, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateIn(List<String> values) {
            addCriterion("pldate in", values, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateNotIn(List<String> values) {
            addCriterion("pldate not in", values, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateBetween(String value1, String value2) {
            addCriterion("pldate between", value1, value2, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldateNotBetween(String value1, String value2) {
            addCriterion("pldate not between", value1, value2, "pldate");
            return (Criteria) this;
        }

        public Criteria andPldescriptionIsNull() {
            addCriterion("pldescription is null");
            return (Criteria) this;
        }

        public Criteria andPldescriptionIsNotNull() {
            addCriterion("pldescription is not null");
            return (Criteria) this;
        }

        public Criteria andPldescriptionEqualTo(String value) {
            addCriterion("pldescription =", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionNotEqualTo(String value) {
            addCriterion("pldescription <>", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionGreaterThan(String value) {
            addCriterion("pldescription >", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("pldescription >=", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionLessThan(String value) {
            addCriterion("pldescription <", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionLessThanOrEqualTo(String value) {
            addCriterion("pldescription <=", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionLike(String value) {
            addCriterion("pldescription like", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionNotLike(String value) {
            addCriterion("pldescription not like", value, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionIn(List<String> values) {
            addCriterion("pldescription in", values, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionNotIn(List<String> values) {
            addCriterion("pldescription not in", values, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionBetween(String value1, String value2) {
            addCriterion("pldescription between", value1, value2, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPldescriptionNotBetween(String value1, String value2) {
            addCriterion("pldescription not between", value1, value2, "pldescription");
            return (Criteria) this;
        }

        public Criteria andPlownerIsNull() {
            addCriterion("plowner is null");
            return (Criteria) this;
        }

        public Criteria andPlownerIsNotNull() {
            addCriterion("plowner is not null");
            return (Criteria) this;
        }

        public Criteria andPlownerEqualTo(String value) {
            addCriterion("plowner =", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerNotEqualTo(String value) {
            addCriterion("plowner <>", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerGreaterThan(String value) {
            addCriterion("plowner >", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerGreaterThanOrEqualTo(String value) {
            addCriterion("plowner >=", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerLessThan(String value) {
            addCriterion("plowner <", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerLessThanOrEqualTo(String value) {
            addCriterion("plowner <=", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerLike(String value) {
            addCriterion("plowner like", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerNotLike(String value) {
            addCriterion("plowner not like", value, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerIn(List<String> values) {
            addCriterion("plowner in", values, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerNotIn(List<String> values) {
            addCriterion("plowner not in", values, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerBetween(String value1, String value2) {
            addCriterion("plowner between", value1, value2, "plowner");
            return (Criteria) this;
        }

        public Criteria andPlownerNotBetween(String value1, String value2) {
            addCriterion("plowner not between", value1, value2, "plowner");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plog
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plog
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}