package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.qid
     *
     * @mbg.generated
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.pkid
     *
     * @mbg.generated
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.uimg
     *
     * @mbg.generated
     */
    private String uimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.des
     *
     * @mbg.generated
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.qtime
     *
     * @mbg.generated
     */
    private String qtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.qid
     *
     * @return the value of question.qid
     *
     * @mbg.generated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.qid
     *
     * @param qid the value for question.qid
     *
     * @mbg.generated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.pkid
     *
     * @return the value of question.pkid
     *
     * @mbg.generated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.pkid
     *
     * @param pkid the value for question.pkid
     *
     * @mbg.generated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.uid
     *
     * @return the value of question.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.uid
     *
     * @param uid the value for question.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.uimg
     *
     * @return the value of question.uimg
     *
     * @mbg.generated
     */
    public String getUimg() {
        return uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.uimg
     *
     * @param uimg the value for question.uimg
     *
     * @mbg.generated
     */
    public void setUimg(String uimg) {
        this.uimg = uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.des
     *
     * @return the value of question.des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.des
     *
     * @param des the value for question.des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.qtime
     *
     * @return the value of question.qtime
     *
     * @mbg.generated
     */
    public String getQtime() {
        return qtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.qtime
     *
     * @param qtime the value for question.qtime
     *
     * @mbg.generated
     */
    public void setQtime(String qtime) {
        this.qtime = qtime;
    }
}