package com.example.webpet.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uage
     *
     * @mbg.generated
     */
    private Integer uage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ugender
     *
     * @mbg.generated
     */
    private Integer ugender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uimg
     *
     * @mbg.generated
     */
    private String uimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbg.generated
     */
    private Integer admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uage
     *
     * @return the value of user.uage
     *
     * @mbg.generated
     */
    public Integer getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uage
     *
     * @param uage the value for user.uage
     *
     * @mbg.generated
     */
    public void setUage(Integer uage) {
        this.uage = uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ugender
     *
     * @return the value of user.ugender
     *
     * @mbg.generated
     */
    public Integer getUgender() {
        return ugender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ugender
     *
     * @param ugender the value for user.ugender
     *
     * @mbg.generated
     */
    public void setUgender(Integer ugender) {
        this.ugender = ugender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uimg
     *
     * @return the value of user.uimg
     *
     * @mbg.generated
     */
    public String getUimg() {
        return uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uimg
     *
     * @param uimg the value for user.uimg
     *
     * @mbg.generated
     */
    public void setUimg(String uimg) {
        this.uimg = uimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admin
     *
     * @return the value of user.admin
     *
     * @mbg.generated
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admin
     *
     * @param admin the value for user.admin
     *
     * @mbg.generated
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }
}