package com.example.webpet.mapper;

import com.example.webpet.entity.Pdcomment;
import com.example.webpet.entity.PdcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PdcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    long countByExample(PdcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int deleteByExample(PdcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer comid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int insert(Pdcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int insertSelective(Pdcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    List<Pdcomment> selectByExample(PdcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    Pdcomment selectByPrimaryKey(Integer comid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pdcomment record, @Param("example") PdcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pdcomment record, @Param("example") PdcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pdcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdcomment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pdcomment record);
}
