package com.example.webpet.mapper;

import com.example.webpet.entity.Pdynamic;
import com.example.webpet.entity.PdynamicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PdynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    long countByExample(PdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int deleteByExample(PdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int insert(Pdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int insertSelective(Pdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    List<Pdynamic> selectByExample(PdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    Pdynamic selectByPrimaryKey(Integer pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pdynamic record, @Param("example") PdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pdynamic record, @Param("example") PdynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pdynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pdynamic record);
}
