package com.example.webpet.mapper;

import com.example.webpet.entity.Petknowledge;
import com.example.webpet.entity.PetknowledgeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PetknowledgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    long countByExample(PetknowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int deleteByExample(PetknowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int insert(Petknowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int insertSelective(Petknowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    List<Petknowledge> selectByExample(PetknowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    Petknowledge selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Petknowledge record, @Param("example") PetknowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Petknowledge record, @Param("example") PetknowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Petknowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petknowledge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Petknowledge record);
}
