package com.example.webpet.mapper;

import com.example.webpet.entity.Plog;
import com.example.webpet.entity.PlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    long countByExample(PlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int deleteByExample(PlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer plid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int insert(Plog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int insertSelective(Plog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    List<Plog> selectByExample(PlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    Plog selectByPrimaryKey(Integer plid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Plog record, @Param("example") PlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Plog record, @Param("example") PlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Plog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Plog record);
}
